export const SITE = {
  website: "https://gc1175383875.github.io/",
  author: "Orange Gan",
  profile: "https://gc1175383875.github.io/",
  desc: "爱编程的橙子",
  title: "Orange Blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/gc1175383875/gc1175383875.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
  layoutStyle: "sidebar",
} as const;
